#pragma once
#include "sdkconfig.h"
#include "esp_camera.h"

#define APP_HOSTNAME        CONFIG_APP_HOSTNAME
#define SLAVE_MDNS_HOST     CONFIG_SLAVE_MDNS_HOST

#define TRIGGER_GPIO        CONFIG_TRIGGER_GPIO

#define SD_MOUNT_POINT      CONFIG_SD_MOUNT_POINT
#define WWW_DIR             CONFIG_WWW_DIR
#define CAPTURES_DIR        CONFIG_CAPTURES_DIR
#define REGPROFILES_DIR     CONFIG_REGPROFILES_DIR

#define WIFI_SSID           CONFIG_WIFI_SSID
#define WIFI_PASS           CONFIG_WIFI_PASS
#define WIFI_MAX_RETRY      CONFIG_WIFI_MAX_RETRY

// Streaming defaults
#define STREAM_DEFAULT_FRAMESIZE FRAMESIZE_SVGA
#define STREAM_DEFAULT_JPEG_QUALITY 12
#define STREAM_DEFAULT_FB_COUNT 2

// Capture defaults (API can override)
#define CAPTURE_DEFAULT_FRAMESIZE FRAMESIZE_UXGA
#define CAPTURE_DEFAULT_PIXFORMAT PIXFORMAT_JPEG
#define CAPTURE_DEFAULT_JPEG_QUALITY 10
